### PR TITLE
fix(generator): unnecessary escape character in vue.config.js, fixes #20

### LINKED ISSUE #20: error: Unnecessary escape character: \/ (no-useless-escape) at vue.config.js
**Describe the bug**
After running `vue add quasar`, I am getting these errors:
```bash
⠋  Running completion hooks...error: Unnecessary escape character: \/ (no-useless-escape) at vue.config.js:11:31:
   9 |   },
  10 | 
> 11 |   transpileDependencies: [/[\\\/]node_modules[\\\/]quasar[\\\/]/]
     |                               ^
  12 | };
  13 | 


error: Unnecessary escape character: \/ (no-useless-escape) at vue.config.js:11:49:
   9 |   },
  10 | 
> 11 |   transpileDependencies: [/[\\\/]node_modules[\\\/]quasar[\\\/]/]
     |                                                 ^
  12 | };
  13 | 


error: Unnecessary escape character: \/ (no-useless-escape) at vue.config.js:11:61:
   9 |   },
  10 | 
> 11 |   transpileDependencies: [/[\\\/]node_modules[\\\/]quasar[\\\/]/]
     |                                                             ^
  12 | };
  13 | 


3 errors found.

```

**To Reproduce**
1. add a vue cli project: `vue create my-project`
2. `cd my-project`
3. Add quasar plugin: `vue add quasar`

`vue.config.js` now contains:
```js
  transpileDependencies: [/[\\\/]node_modules[\\\/]quasar[\\\/]/]
```

### PR DESCRIPTION
**Pull request by nklayman**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [ ] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar/tree/dev/docs) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

The text replace is necessary since the escape character is added automatically somewhere, the [generator doesn't have it](https://github.com/quasarframework/vue-cli-plugin-quasar/blob/dev/generator/index.js#L85).

### CODE REVIEW

**Comment by yusufkandemir** [comment]
> The text replace is necessary since the escape character is added automatically somewhere, the [generator doesn't have it](https://github.com/quasarframework/vue-cli-plugin-quasar/blob/dev/generator/index.js#L85).

I tried to track down why this was happening and saw that they use [javascript-stringify](https://www.npmjs.com/package/javascript-stringify) to [stringify things](https://github.com/vuejs/vue-cli/blob/0ca37b745340248c97db1259681cb36c4c445359/packages/%40vue/cli/lib/util/configTransforms.js#L38). And [javascript-stringify](https://www.npmjs.com/package/javascript-stringify) seems to add and extra slash probably because of [this logic](https://github.com/blakeembrey/javascript-stringify/blob/36e5f8bf875b425e220927d215149c123825bb76/src/quote.ts#L22)(the code seems complicated so I couldn't dig deeper but found [this](https://github.com/blakeembrey/javascript-stringify/blob/d4a81f43136b0aa50a0c5d99efab4fe6dd5a9872/src/index.spec.ts#L91) in their tests).

I created a simple test script to validate:
```js
const { stringify } = require('javascript-stringify')

console.log(stringify({
  vue: {
    transpileDependencies: [
      /[\\/]node_modules[\\/]quasar[\\/]/
    ]
  }
}))
```

I also searched for alternative ways to push to `transpileDependencies` and found [vue-cli-plugin-vuetify's usage](https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/ca0a0b42e683c0306689f95cdff20f90a5c65385/generator/tools/vuetify.js#L74-L76). Which is most close to #21.

**Comment by nklayman** [comment]
They overwrite the file completely, which could cause issues with formatting and comments. I think it is better to just replace the part of the file.

**Comment by yusufkandemir** [comment]
You are right, but we can just change our current logic a little bit by replacing the regex with a string 'quasar'. Vue CLI generates the correct regex out of that string, you can check [here](https://github.com/vuejs/vue-cli/blob/759d77fd5c5056c9674b0370b0ffb7702a7ff70c/packages/%40vue/cli-plugin-babel/index.js#L7-L11). It would be a much simpler and clearer approach IMO.

**Comment by nklayman** [comment]
@rstoenescu since vue cli handles the path automatically, it seems like it would be fine the just pass in the string. Do you think there will be any issues with that?

**Comment by rstoenescu** [comment]
Thank you both for the comments and the PR!
Since Yusuf mentioned about [how vue-cli handles this](https://github.com/vuejs/vue-cli/blob/759d77fd5c5056c9674b0370b0ffb7702a7ff70c/packages/%40vue/cli-plugin-babel/index.js#L7-L11), decided to merge https://github.com/quasarframework/vue-cli-plugin-quasar/pull/21

**Pull request closed without merging**
